In [1]:
import pandas as pd
df_raw = pd.read_csv('../output/data_cleaned/Mian_uti_m1_USED.csv')

df_raw

     Unnamed: 0 patient_id        date
0             0      eca1f  2019-05-09
1             1      eca1f  2019-05-11
2             2      eca1f  2019-05-15
3             3      6b29b  2019-04-19
4             4      6b29b  2019-04-25
..          ...        ...         ...
260         260      e8a78  2019-06-19
261         261      e8a78  2019-06-20
262         262      e8a78  2019-06-21
263         263      e8a78  2019-06-23
264         264      c55f8  2019-06-05

[265 rows x 3 columns]

In [3]:
df_uti = df_raw.copy()

df_uti['date'] = pd.to_datetime(df_raw['date'])
df_uti['dates'] = df_uti['date'].dt.date
df_uti

     Unnamed: 0 patient_id       date       dates
0             0      eca1f 2019-05-09  2019-05-09
1             1      eca1f 2019-05-11  2019-05-11
2             2      eca1f 2019-05-15  2019-05-15
3             3      6b29b 2019-04-19  2019-04-19
4             4      6b29b 2019-04-25  2019-04-25
..          ...        ...        ...         ...
260         260      e8a78 2019-06-19  2019-06-19
261         261      e8a78 2019-06-20  2019-06-20
262         262      e8a78 2019-06-21  2019-06-21
263         263      e8a78 2019-06-23  2019-06-23
264         264      c55f8 2019-06-05  2019-06-05

[265 rows x 4 columns]

In [6]:
# get daily count of agitation episodes
daily_counts = df_uti.groupby(['patient_id', 'dates']).size().reset_index(name='count')

daily_counts.columns = ['patient_id', 'date', 'uti_happen']
daily_counts.to_csv('../output/data_cleaned/uti_daily.csv', index=False)
daily_counts

    patient_id        date  uti_happen
0        0697d  2019-06-30           1
1        099bc  2019-06-05           1
2        099bc  2019-06-07           1
3        099bc  2019-06-18           1
4        099bc  2019-06-26           1
..         ...         ...         ...
260      f220c  2019-05-12           1
261      f220c  2019-05-19           1
262      f220c  2019-05-31           1
263      f220c  2019-06-14           1
264      fd100  2019-06-28           1

[265 rows x 3 columns]